### ISSUE TITLE
Double space then return

### ISSUE THREAD

**Issue by alex-kovac** [slang800/atom-tidy-markdown#10]
Hi slang800, great work on this plugin! A smallish issue... Daring Fireball's Markdown syntax says: "When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return." As it is, _atom-tidy-markdown_ "tidifies" such a forced line break into a paragraph break... Is there a chance that the forced line breaks could be preserved?

**Comment by jorng** [comment]
Agree!  It should not add a `<br>` in my markdown. This defeats the readability.

**Comment by notslang** [comment]
closing because I wrote a reply over in https://github.com/slang800/atom-tidy-markdown/issues/24
