### ISSUE TITLE
please don't format text in code

### ISSUE THREAD

**Issue by justqb** [slang800/atom-tidy-markdown#11]
## my text:
# t1
- text 1

``` java
/**
* some comment
*/
public static main(String[] args){
    // do something
}
```

---
## after save and format by tidy package
# t1
- text 1
- ```java
- /**
- some comment
- */
- public static main(String[] args){
- // do something
- }
## \- ```

that is a big problem!

**Comment by justqb** [comment]
sorry . markdown text is parsed by github
pictures is followed
![1](https://cloud.githubusercontent.com/assets/7219591/8178709/7a9cc21a-1443-11e5-9ab7-372c5c6db538.PNG)
![2](https://cloud.githubusercontent.com/assets/7219591/8178708/7a9bf1a0-1443-11e5-9ef2-ae468503e769.PNG)

**Comment by notslang** [comment]
Yeah, that's a problem with Markdown itself:

![screenshot from 2015-06-17 10 46 40](https://cloud.githubusercontent.com/assets/1049204/8210039/276fd654-14de-11e5-8cad-7c0f08dbd27f.png)

Maybe you mean this:

![screenshot from 2015-06-17 10 50 04](https://cloud.githubusercontent.com/assets/1049204/8210156/aff4e1d6-14de-11e5-9987-5adbe830b8b5.png)

Or this?:

![screenshot from 2015-06-17 10 49 35](https://cloud.githubusercontent.com/assets/1049204/8210170/c0c02dfe-14de-11e5-8e3b-914fc4814cf6.png)

**Comment by notslang** [comment]
closing due to lack of reply
