### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by kmcginnes** [slang800/atom-tidy-markdown#2]
I also got this. This does not affect functionality as far as I can tell.

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
new TidyMarkdown (/Users/krismcginnes/.atom/packages/tidy-markdown/lib/tidy-markdown.coffee:11:29)
```

**Comment by notslang** [comment]
I think this is fixed with 576a764c2013dc6340ea8e875beb5a4206320b44
