### ISSUE TITLE
Keep first and last pipe in tables

### ISSUE THREAD

**Issue by rugk** [slang800/atom-tidy-markdown#21]
I think similar to [markdown-table-formatter](https://atom.io/packages/markdown-table-formatter) it would be great if you could keep the first and last pipe in a table.

**Comment by hawkeyetwolf** [comment]
Added issue ([#22](https://github.com/slang800/tidy-markdown/issues/22)) in the base repo. This issue can be used for exposing the behavior as a configuration setting in the atom plugin.

**Comment by rugk** [comment]
:+1:

**Comment by notslang** [comment]
Closing because https://github.com/slang800/tidy-markdown/issues/22 is the correct place for this.
