### ISSUE TITLE
Should not convert links

### ISSUE THREAD

**Issue by rugk** [slang800/atom-tidy-markdown#28]
Links like 

``` md
https://github.com/slang800/atom-tidy-markdown/issues/new
```

are converted into

``` md
[https://github.com/slang800/atom-tidy-markdown/issues/new](https://github.com/slang800/atom-tidy-markdown/issues/new)
```

which is completely unnecessary and reduces readability by increasing the length of. So this should not done anymore or there should be at least a checkbox to deselect this.

**Comment by notslang** [comment]
Yeah, you're right... we don't even need an option for that, there's no reason to write a link like that. Wanna PR a fix for it in [tidy-markdown](https://github.com/slang800/tidy-markdown)?

**Comment by rugk** [comment]
~~Is `tidy-markdown` a fork of `atom-tidy-markdown`?~~

**Edit:** Ah no it is the internal part. Sorry, but I'm not that experienced in JavaScript.

**Comment by rugk** [comment]
Moving issue to https://github.com/slang800/tidy-markdown/issues/21.
