### ISSUE TITLE
Formatting breaks front matter

### ISSUE THREAD

**Issue by benbalter** [slang800/atom-tidy-markdown#3]
This package sounds like exactly what I've been looking for for a long time, but unfortunately, it doesn't play nicely with markdown files that contain YAML front matter (e.g., Jekyll sites, used in places like GitHub pages).

YAML front matter might look like this:

``` md

---
title: "Awesome markdown file"

---

My content
```

Right now, this would create an HR followed by an H1. Instead, it'd be great if the plugin (or upstream library) could split the content on `/^---\n.*?\n---\n\n/m` and not act on the first element, if present.

**Comment by notslang** [comment]
Yeah, this is worth supporting in tidy-markdown - I'll add that.

**Comment by notslang** [comment]
@benbalter - if you update, this feature will now work
