### ISSUE TITLE
Disabling tidy markdown does not actually disable the plugin

### ISSUE THREAD

**Issue by mb-dev** [slang800/atom-tidy-markdown#30]
I tried to disable tidy markdown after encountering some bugs (like --- turning into a whole line of breaks that was reported here, and sub list spacing that others reported). However the plugin keeps running and on every save I still get things changed. I had to close atom (which ended up not responding) and had to be killed.

Please try the disable button and see if it actually works.

**Comment by jbnv** [comment]
+1
