### ISSUE TITLE
Unwanted Auto Transfer 

### ISSUE THREAD

**Issue by hairui219** [slang800/atom-tidy-markdown#33]
When I use <code>& lt;(with out the space)</code> in text, it was automatically transferred to <code><</code> sign. 

I am writing a doc and want to display inline raw html in it, this made my code disappear.

**Comment by notslang** [comment]
That is to be expected, when I write &lt; (`&lt;`) in Markdown it will be automatically converted to the less-than sign during rendering. If you want to keep the `&lt;` code, you should wrap it in back-ticks. Also, you should be able to escape a sequence of characters with a `\`, but that doesn't seem to work, so I made an issue over here: https://github.com/slang800/tidy-markdown/issues/24
