### ISSUE TITLE
nested blockquotes

### ISSUE THREAD

**Issue by xaeo** [slang800/atom-tidy-markdown#41]
replace >>  by > auto.  but i wanna use >>

**Comment by notslang** [comment]
You mean for blockquotes? Could you post some example markdown with the given output and the expected output?

**Comment by xaeo** [comment]
Before：
![before](http://7xrh78.com1.z0.glb.clouddn.com/ab1cb95b8b0aae1a1206a38c20997204.png)
After（tidy run）：
![after](http://7xrh78.com1.z0.glb.clouddn.com/b95651057c5ca13ed33fca6cac9cb0a9.png)

**Comment by notslang** [comment]
Oh! I'll add a test case for that & it should be fixed in https://github.com/slang800/tidy-markdown/pull/26

**Comment by notslang** [comment]
Added  the test case in https://github.com/slang800/tidy-markdown/pull/26/commits/245d433de5f43c79eb67f72f74aea31b6037bc0a & it passes
