### ISSUE TITLE
Data loss due to over-zealous clean up of `<img>` tags

### ISSUE THREAD

**Issue by Superbest** [slang800/atom-tidy-markdown#44]
I noticed that `<img>` tags seem to be corrected too aggressively.

I have several files where I include images with something like `<img src="my image.png" width=500>` because the image itself is too large for a nice layout. Tidy Markdown converts these into `![](my image.png)`. This strips the `width` information, and disrupts layout.

Possible solutions (pick one:
- Leave HTML tags alone and don't tidy them at all.
- Don't tidy `<img>` tags.
- Check the tag and only tidy if there are no properties besides `src`.
- Make HTML tag tidying optional behavior.

**Comment by notslang** [comment]
moved to https://github.com/slang800/tidy-markdown/issues/28 (this repo is just a wrapper around tidy-markdown)
