### ISSUE TITLE
Tidy Markdown Destroys <PRE> tags

### ISSUE THREAD

**Issue by kingmesal** [slang800/atom-tidy-markdown#48]
Any chance that there could be a checkbox added to enable / disable the cleaning of a `<pre>` tag within this plugin? We have cases where there are attributes on pre tags and this blows them away and drops in a code block. We have to disable tidy markdown because of this.

**Comment by notslang** [comment]
see: slang800/tidy-markdown#28 (I'd gladly take a PR to fix this)

Also, what are your pre tag attributes for?
