### ISSUE TITLE
Strips <a> tags of extra attributes

### ISSUE THREAD

**Issue by michaelabon** [slang800/atom-tidy-markdown#51]
When using 3.0.1, tidy-markdown incorrectly converted anchors that contained extra attributes

This git diff shows the conversion, where `+` marks the conversion result and `-` marks the original source material.

```
+ []()
- <a id="prereq"></a>
```

**Comment by notslang** [comment]
see: https://github.com/slang800/tidy-markdown/issues/28 (I'd gladly take a PR to fix this)
