### ISSUE TITLE
No Wrapping

### ISSUE THREAD

**Issue by jeremie-lesage** [slang800/atom-tidy-markdown#52]
The tidy force no wrapping. I lost my pretty manually wrapping. Can you add an option to disable this feature ?

Thanks for this addon

**Comment by notslang** [comment]
See https://github.com/slang800/tidy-markdown/issues/30. I suppose I'd take a PR for this, but in general I think it's a bad idea for the reasons outlined in https://github.com/slang800/tidy-markdown/issues/16
