### ISSUE TITLE
Destroys relative links to other files.

### ISSUE THREAD

**Issue by rugk** [slang800/atom-tidy-markdown#57]
Original:

``` md
See [otherfile.md](otherfile.md) for more information.
```

After tidy:

``` md
See <otherfile.md> for more information.
```

However this link does not work: 
- original: [otherfile.md](otherfile.md)
- tidy: <otherfile.md>

**Comment by notslang** [comment]
Moved to https://github.com/slang800/tidy-markdown/issues/38
