### ISSUE TITLE
Separator lines within tables are not automatically resized

### ISSUE THREAD

**Issue by DenisKramer** [slang800/atom-tidy-markdown#60]
Additional separator lines in tables are not automatically resized to match the header separator.

Example:
```
ColA | ColB
---- | ----
A1   | B1
--   | --
A2   | B2
```
should be 

```
ColA | ColB
---- | ----
A1   | B1
---- | ----
A2   | B2
```

**Comment by notslang** [comment]
On github that renders into this:

![1488583142](https://cloud.githubusercontent.com/assets/1049204/23572568/f1dfd49c-003d-11e7-9b31-b362c2c8a168.png)

What are you using that supports additional separator lines?

**Comment by notslang** [comment]
Looks like kramdown is the only implementation that handles this: http://johnmacfarlane.net/babelmark2/?text=ColA+%7C+ColB%0A----+%7C+----%0AA1+++%7C+B1%0A----+%7C+----%0AA2+++%7C+B2

You could look at getting it added to the [commonmark spec](https://talk.commonmark.org/), but right now I think adding support for this would cause more problems than it solves.
