### ISSUE TITLE
Lists numbering incorrectly

### ISSUE THREAD

**Issue by rtvenge** [slang800/atom-tidy-markdown#7]
I'm seeing some issues with multiple lists in one file where its thinking there is only one ordered list. Here is a reduced test case to reproduce the problem:

```
# title
1. list item
2. list item
3. list item

# other title
1. list item
3. list item
```

…gets changed to:

```
# title
1. list item
2. list item
3. list item

# other title
4. list item
5. list item
```

Expected result is for the second list numbers to be changed to 1. and 2. This also doesn't work if the second list is numbered correctly (1. and 2.).

Let me know if you need any other information from me.

Thanks for your work on this plugin!

**Comment by rtvenge** [comment]
As I'm looking at this a little more, I didn't realize you are just using the tidy-markdown node_module in this plugin. I tried updating to v0.3.0, but the problem still persists. Is this something I should report to [tidy-markdown](https://github.com/slang800/tidy-markdown)?

**Comment by notslang** [comment]
Technically, yes - but I just pushed a fix for this, so don't worry about it: https://github.com/slang800/tidy-markdown/commit/53fb01bb2f044fc6877419ae2a2dbcf9a4ad13d7

**Comment by notslang** [comment]
And if you update to v0.3.1 it should be fixed

**Comment by rtvenge** [comment]
Thanks @slang800 for the quick response and fix!
